oauth2:
  client:
    registration:
      kakao:
        clientId: 1cb529af744df205a39cff030825961a
        clientSecret: m5Dp1jUWkpe0BLFiKGXL7AbZTqKzZRV6
        scope: profile_nickname, account_email, age_range
        clientName: Kakao
        authenticationMethod: POST

      naver:
        clientId: NK0288EkGrDIjENufyxP
        clientSecret: U_ezxP8a96
        scope: name, email
        clientName: Naver
        authenticationMethod: POST

    provider:
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response