spring:

  jpa:
    properties:
      hibernate:
        format_sql: true  #To beautify or pretty print the SQL
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 2MB #file upload size restriction

  profiles:
    include: oauth

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG #show parameter binding

file:
  dir: back_data/images/